language: php

php:
  - 5.6
  - 7.0
  - 7.1

sudo: false

install: travis_retry composer install --no-interaction --prefer-source

script: vendor/bin/phpcs --standard=PSR2 ./src

script: vendor/bin/phpunit --verbose
